### ISSUE TITLE
Edit Tutor's Calendar

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#1]
### Tasks-

- [x] Logged in tutor can change their availability on their calendar by clicking red slot to change to dark blue (or available) or vise versa. 
- [x] Once the tutor changes their schedule its added to the database and the loaded in the tutor's calendar.

 ### Tests-
- [x] Once tutor logs in if no schedule had been set previously it should all be same color as background. A tutor can click on the slots and change them to a darker tone .  
- [x] Once a change has been made tutor can now click submit and submit their schedule.
- [x] This change will be updated on the database and loaded on the tutor's database and the tutor can see the change.
