### ISSUE TITLE
Make appointment page for students

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#115]
### Tasks

- [x] add appt database
- [x] create dummy appts to load
- [x] load said appts to student appt page

### Tests

- all existing appts with the student_id are loaded into the page, navigation back to profile exists
- if an appt is deleted, the appt page updates
