### ISSUE TITLE
Initial Information before appointment

### ISSUE THREAD

**Issue by sedrehman** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#131]
### Tasks:
When making an appointment with a tutor, the student is asked to provide -
 - [x] their previous grades on that class
 - [x] next exam / test / quiz date

 ### Tests
 - [x] when student is trying to make appointment the above information is asked on a new page
 - [x] once student enter those information they are added to database .
 - [x] appointment doesn't require you to enter these information. You can submit without entering anything and if that's the case then nothing will be added to the DB
