### ISSUE TITLE
After appointment has been made, enable student to enter grades for that course

### ISSUE THREAD

**Issue by sedrehman** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#132]
### Tasks:
When the student  logs  in he/she can enter their grades for courses they made appointments for  -
 - [x] if they have no previous grade then a new grade is added to specified course
 - [x] else a new grade is appended to the previous grades

 ### Tests
 - [x] new grades shows up on the db
 - [x] if no appointment was made for that course, show error msg.
