### ISSUE TITLE
As a tutor, I will enter my zoom meeting ID at prompt so students in quarantine can still meet with me.

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#146]
### Tasks: 
- [x] Create a button for tutors that takes them to an 'add-zoom' page where they can enter their Zoom Meeting Room URL
- [x] On this add-zoom page, have a button that takes tutors to the Zoom Sign-in Page in a new tab
- [x] Create an instruction guide on the add-zoom page to guide tutors on what info they need to fetch and how to do so. 
- [x] Create a string check to make sure entered url is a Zoom Meeting Room url on add-zoom page.
- [x] Create a Save button that updates zoom_link information in the database if url is valid.  This button also redirects to the tutor's view of their own profile 
- [x] Display the tutor's Zoom Meeting Room URL if it is present in database above the button to add or edit their Zoom Link
- [x] On the student side of a tutor's profile, create a button that takes student to the Zoom Meeting url the tutor entered into the database
- [x] If no url is present, button to go to tutor's Meeting Room is not present. 

### Acceptance Tests: 
- Log in as a tutor and navigate to your profile
- A button that reads "Add/Edit Zoom Link" should be visible below the tutor profile image
- When this button is clicked, tutor should be taken to a new 'add-zoom' page where they can add their zoom link
- On the 'add-zoom' page, a 'Go to Zoom Sign in' button should be visible that redirects tutors to the Zoom Sign In page. 
- On the 'add-zoom' page, instructions should be visible on where to find a tutor's Zoom Meeting Room URL and a textbox should be present.  
- On the 'add-zoom' page a "Save" button should be visible that, when click, updates info in the database and redirects tutor to their profile. [If url entered in textbox isn't from Zoom or is too short, an error message should appear on page]
- On the tutor's profile, if a url is present in the database, it shoudl appear above the "Add/Edit Zoom Link" button 
- 
- From the student's side, Log into a student profile. 
- Find a tutor with a Zoom Link in the database. 
- Ensure a "Go to this Tutors Zoom Meeting Room" button is present that redirects students to the url entered in database
- Find a tutor with NO Zoom Link in database and visit their profile. 
- Ensure the "Go to this Tutors Zoom Meeting Room" button is not present on this profile page
