### ISSUE TITLE
As a tutor, I want students to get banned if they cancel too many appointment, so that they dont mess with my schedule

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#162]
### Tasks:
- [x] [Implement banning system](<https://app.zenhub.com/workspaces/jalapenocrisp-workspace-5e39fb3b7739b93d0f5beb9f/issues/cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp/163>)

 ### Acceptance Tests:
 - [x] clicking cancel increments cancel numbers in student's database.
 - [x] clicking complete increments complete numbers in student's database.
 - [x] Go to UBTutoring, log is as - 
username - syedrehma@buffalo.edu
password - Hello123!

Currently Syed has 11 completes and 11 cancels. Navigate "My Appointments" where you will see Syed's appointments. If there are none, simply make one. Now once there is an appointment, cancel it by clicking "X" icon. Now navigate to where it says UBTutoring on the top. Try to log in again and you will see, that it won't let you, since Syed now has more cancellation than completion!
