### ISSUE TITLE
Implement Banning system

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#163]
### Tasks:
- [x] add cancellation rate to students profile (count cancelled appointments)
- [x] add completion rate to students profile (count completed appointments)
- [x] disable students from logging in if their cancellation is higher than completion.
- [x] initially give new students 10 completion points.
- [x] add a check in login for banned emails, display a message to contact admin@ubtutoring.com to plead their case to be unbanned
- [x] Redirect student to index page when they cancel an appointment and reach a Completion Rate of less than 50%

 ### Tests:
 - [x] clicking cancel increments cancel numbers in student's database.
 - [x] clicking complete increments complete numbers in student's database.
 - [x] On a student account, cancel an appointment that makes the cancellation rate higher than completion rate and ensure that the student is logged out of their account. 
 - [x] students with lower than 50% Completion rates aren't allowed to log in as they are banned. When tried to log in, it will give you an error message and block the log in.  Ensure this happens when attempting login as a banned student.
