### ISSUE TITLE
As a professor, I will log in the UBTutoring as "professor" to view all the tutors' ratings so I can decide if I want to hire a tutor as a TA.

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#164]
### Tasks 

- [x] create a page that shows the a list of tutors based on their ratings
- [x] create a page where a professor will enter their email so that they can log in 
- [x] create a button that will allow professors to access the site to see a list of tutors  

### Acceptance Tests:

- As a user of the site, go to the navigation links and click access as a professor
- Make sure you are routed to a page and prompted to enter a ub email
- Enter a UB email and make sure you are routed to a page that shows all the tutors based on their ratings in descending order.
