### ISSUE TITLE
Tutor adding availability  

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#17]
### Tasks
- [x] Tutors can add/ change availability on their schedule  (UI Only)

### Tests
- [x] clicking on add events let you add a schedule for any day of the week
- [x] removing schedule for a day removes it from the calendar.

**Comment by sedrehman** [comment]
Starting on issue #17
