### ISSUE TITLE
As a banned student, I want to be able to appeal to be un-banned from the site so that I may get back to the site

### ISSUE THREAD

**Issue by sedrehman** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#174]
### Tasks:
 - [x] Create a student-appeal page 
 - [x] Enable banned students to send appeal to admin

 ### Acceptance Tests:
 - [x] As a banned student, attempt to log in , you will be denied, then given a link to "contact us". Where you must click on this link. This will take you a new page where you can submit an appeal. 
 - [x] Upon submitting an appeal, a message in red will appear if the appeal has been successfully made. 
 - [x] You will receive an email with this appeal message as well as the admins on the site.

Here's link to the site where you test this yourself [-UBTutoring](https://www-student.cse.buffalo.edu/CSE442-542/2020-spring/cse-442i/cse442/cse442-semester-project-jalapenocrisp/)
