### ISSUE TITLE
Add Completion Rate to Student Profile

### ISSUE THREAD

**Issue by TKTre** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#181]
### Tasks:
- [x] Add table row with Completion Rate on Student profile 
- [x] Add title to Completion Rate telling students what penalties come with a low completion rate(lower than half)
- [x] Have Completion Rate pull from the database

### Tests: 
- Log in as a student and navigate to a tutor's profile to make an appointment
- Cancel the appointment and navigate back to your profile to ensure changes are accurately reflected (denominator increases by one) 
- Go to another tutor's profile and make another appointment.  
- Mark this appointment as completed and then go back to your profile. 
- Ensure numerator and denominator have each increased by one
