### ISSUE TITLE
Create student-appeal page

### ISSUE THREAD

**Issue by sedrehman** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#183]
### Tasks:
 - [x] create a page called student-appeal that lets students appeal to be un-banned
 - [x] banned students are can go to student-appeal page when they try to log in
 - [x] upon submitting send appeal in the form of email to the student who sent it and the admins.

 ### Tests:
 - [x] As a banned student, once attempted to log in, a link that says "contact us" will appear. Where you must click on this link.
 - [x] Clicking this link will take you to the appeal-page where you can submit an appeal.
 - [x] upon submitting an appeal, students sees a red text with message telling the student that the appeal has been successfully made. 
 - [x] upon submitting an appeal, student and admins are sent email with the appeal.
