### ISSUE TITLE
As a UB student I want to see a good looking interface so that it encourages me to use UBtutoring more.

### ISSUE THREAD

**Issue by kesamercy** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#184]
### Tasks:
 - [x] change color theme for the website
 - [x] make navigation easy to use/find for all pages
 - [x] make the site elements display correctly in mobile view mode
 ### Acceptance Tests:
 - As a user on the platform, hover over the navigation bar and make sure the nav links change color to green 
 - Navigating from page to page and observe that the background is consistent on all pages giving it a uniform theme.
- Check the pages titles and see that they are all green in color of the pages are the same font size besides the main page and the website has a uniform font family.
- When you navigate the site in device mode, the site all the features remain consistent with the page design.
