### ISSUE TITLE
Student Cancel/Complete

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#22]
### Tasks

- [x] save appt status in appt table
- [x] load only upcoming appts in "my appts"
- [x] load all other appts in "past appts"
- [x] add rate button to only completed appts
- [x] email tutor only for cancelled appts

### Acceptance Tests

- completed appts and cancelled appts move to the history page
- only completed appts show "rate tutor" button
- tutor for cancelled appt receives generic email notifying of the student's cancellation
