### ISSUE TITLE
Add Tutor Score to profile

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#27]
### Tasks
- [x] add score to tutor table
- [x] load score from table
- [x] add description on hover

### Tests
- when navigating to tutor profile on tutor or student side, tutor score shows as 0
- when hovering over "Score" the description of the score shows up
