### ISSUE TITLE
As a user of the platform, I should be able to see a Profile Picture when I navigate to my respective profile page

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#28]
### Tasks
- [x] Enable the students to have a profile picture on their student profile page 
- [x] Enable the tutor to have a profile picture on their tutor profile page 

### Acceptance Tests

- [] navigate to the tutor profile page and find the profile picture if one has already been uploaded 
- [] if no image exists use the add button to upload a picture and it should show on the tutor profile when the upload completes.
- [] navigate to the student profile page and find the profile picture if one has already been uploaded 
- [] if no image exists use the add button to upload a picture and it should show on the student profile when the upload completes.
