### ISSUE TITLE
Rating a Tutor on 4 objectives

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#31]
### Tasks
- [x] prompt student after session has been marked as completed on their appointment page to rate corresponding tutor
- [x] choose 1-5 star rating for each category
- [x] rating is averaged in and sent to tutor's data

### Tests
- When rating a tutor as a student, the student will have the ability to rate a tutor on 4 individual qualities: Course knowledge, Timeliness, Communication Skills, and Teaching skills
- Ensure all non-valid entrees (any character/value that's not 1,2,3,4 or 5) return with an error message.
