### ISSUE TITLE
Rating a Tutor as Student

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#32]
### Tasks
- [x] tutor starts at [no rating]
- [x] ratings show underneath profile picture
- [x] ratings retrieved from database
- [x] make page to rate tutor
- [x] tutor rating average is computed correctly
- [x] new rating adds to the tutors database

### Tests
- log in as student and make an appointment with a tutor with no ratings
- rate tutor all 5's
- make another appointment with same tutor
- rate tutor all 1's
- verify tutor rating is 3
