### ISSUE TITLE
Update Search from Database

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#38]
### Task
- [x] load classes into drop down
- [x] load tutors into drop down based on tutor
- [x] load page of tutor from student-view dropdown on "select" page

### Test
-  the profile of the selected tutor shows when select is clicked
- the dropdowns are populated with all the current classes listed in the database 
- the tutors listed when a cs class is chosen are all the tutors that are available to teach that subject
