### ISSUE TITLE
Enable tutor profile edits

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#39]
### Tasks
- [x] create editable table allowing tutor to edit their profile
- [x] ensure that the student view of the profile is uneditable.
- [x] create buttons to save new values

### Tests
- as a tutor, I can edit values in my profile
- a button called "save changes" can be clicked and upon refresh of the page, the new value has replaced the old one.
- Click and type "Graduate" next to title, click save changes, refresh. "Graduate" should be displayed next to title now.
- I can click return to profile and see my edits
