### ISSUE TITLE
Tutor Information(Student View) [Tasks/Tests]

### ISSUE THREAD

**Issue by TKTre** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#48]
### Tasks
- [x] Show tutors info on the tutors page
- [x] ensure information is not editable
- [x] link to calendar view

### Tests 
- User should see the selected tutor's info on the page
- User should not be able to edit the tutor's info
- The page should have a button that links to an un-editable page of the tutor's calendar.
