### ISSUE TITLE
Class Search [Tasks/Tests]

### ISSUE THREAD

**Issue by TKTre** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#49]
### Tasks
- [x] Hard-code subjects
- [x] Hard-code classes
- [x] Hard-code tutors

### Tests
- When the drop down for selecting Department is clicked by a student, user should be able to choose which department they want to search for classes for
- When the drop down bar for Classes is selected, student should see all courses under previously selected department.
- When student clicks the drop down bar for Tutors, all tutors that can tutor for the previously selected class should be visible and choosable by user.
