### ISSUE TITLE
As a student, I will click "Cancel" to cancel an appointment so I can free up a time slot on the tutor's schedule, sending a generic email to the tutor.

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#63]
### Tasks

- add cancel confirmation page
- remove appt from db
- add cancelled appt to history page

### Acceptance Tests

 - [x] cancelled appointments show as cancelled in the database
 - [x] upon cancel, tutor receives an email
 - [x] students have the option to complete appointments
 - [x] both completed and canceled appointments move to history
