### ISSUE TITLE
As a first time tutor, I will sign up so I can login to the website with my credentials.

### ISSUE THREAD

**Issue by jechepenuk** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#67]
### tasks

- [x] write info to database
- [x] tutor_signup -> php and validate checks
- [x] redirect to login

### Acceptance Tests: 
- [ ] New tutors will find the sign-up button on home page
- [ ] After completing sign-up process, tutor will log in with the info entered on sign up page
- [ ] Tutor will be taken to their profile page
