### ISSUE TITLE
Retrieve data from the database

### ISSUE THREAD

**Issue by sedrehman** [cse442-spring-2020-offering/cse442-semester-project-jalapenocrisp#90]
### Tasks
- [x] Given UBIT name and Password, retrieve the tutor's information from the database. 

### Tests
- [x] Correct tutor is returned when valid info is submitted. 
- [x] Error is returned when invalid UBIT and password is submitted.
